name: genomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - requests
  - google-cloud-firestore
  - google-cloud-storage
  - sra-tools
  - pigz
  - fastp
  - bwa-mem2
  - samtools
  - openjdk=17
  - gatk4
  - bcftools
  - bedtools
  - mosdepth
  - wget
  - unzip
  - coreutils
  - pip
  - pip:
      - gsutil
